// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB99YeRX011K3_KlD7Ym3PH9cMiRzGx0aw',
    appId: '1:675699533615:web:8f29f6f4a8cdeada84a3da',
    messagingSenderId: '675699533615',
    projectId: 'owllet-1a544',
    authDomain: 'owllet-1a544.firebaseapp.com',
    storageBucket: 'owllet-1a544.appspot.com',
    measurementId: 'G-4XBW2FTMHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkliw75bvQ78P2m5dvI2wN801YJGNGSDs',
    appId: '1:675699533615:android:8817a7d559d88b8284a3da',
    messagingSenderId: '675699533615',
    projectId: 'owllet-1a544',
    storageBucket: 'owllet-1a544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0twMOT14ueIPFyqgNQMrxrVHjYvNxrC8',
    appId: '1:675699533615:ios:29e7f42c35221dcb84a3da',
    messagingSenderId: '675699533615',
    projectId: 'owllet-1a544',
    storageBucket: 'owllet-1a544.appspot.com',
    iosClientId: '675699533615-94r1mus2hj0j08a3aup2rrfv3rhr8mdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.owllet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0twMOT14ueIPFyqgNQMrxrVHjYvNxrC8',
    appId: '1:675699533615:ios:29e7f42c35221dcb84a3da',
    messagingSenderId: '675699533615',
    projectId: 'owllet-1a544',
    storageBucket: 'owllet-1a544.appspot.com',
    iosClientId: '675699533615-94r1mus2hj0j08a3aup2rrfv3rhr8mdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.owllet',
  );
}
