// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5oHHyhFXKkmXy3avD6Et6B9c3plT7zwI',
    appId: '1:298047915450:web:13898c5b418295940d0983',
    messagingSenderId: '298047915450',
    projectId: 'doge-finances',
    authDomain: 'doge-finances.firebaseapp.com',
    storageBucket: 'doge-finances.appspot.com',
    measurementId: 'G-GFSVERE9RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPSFe1BFupqpLfAKhyMtALxyaIiDVcok8',
    appId: '1:298047915450:android:ed2ecb38ed5833170d0983',
    messagingSenderId: '298047915450',
    projectId: 'doge-finances',
    storageBucket: 'doge-finances.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOV_X-dJYlrsLt-1FxJ0cuI-liRBgkCWo',
    appId: '1:298047915450:ios:6be32d2bbf8dda5f0d0983',
    messagingSenderId: '298047915450',
    projectId: 'doge-finances',
    storageBucket: 'doge-finances.appspot.com',
    iosClientId: '298047915450-1u4v3vqupt9p7ojkblphlsd2o3e9e5ht.apps.googleusercontent.com',
    iosBundleId: 'com.hawkstudio.dogeFinances',
  );
}
